"""add_config_path_to_camera

Revision ID: 42a7b8cf2fa3
Revises: bc795b284007
Create Date: 2026-01-16 01:22:58.494398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42a7b8cf2fa3'
down_revision: Union[str, Sequence[str], None] = 'bc795b284007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('config_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'config_path')
    # ### end Alembic commands ###
