"""rename_session_to_cameranetwork

Revision ID: 4e0c1532e3eb
Revises: c7d2f45f8a11
Create Date: 2026-05-22 00:15:25.391123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e0c1532e3eb'
down_revision: Union[str, Sequence[str], None] = 'c7d2f45f8a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('cameranetwork',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sct_config', sa.JSON(), nullable=True),
    sa.Column('mct_config', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('output_video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_txt_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('total_global_ids', sa.Integer(), nullable=False),
    sa.Column('avg_fps', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallerytrack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('is_mapped', sa.Boolean(), nullable=False),
    sa.Column('cam_id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lost_age', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallerytrack_person_id'), 'gallerytrack', ['person_id'], unique=True)
    op.create_index(op.f('ix_gallerytrack_tracker_id'), 'gallerytrack', ['tracker_id'], unique=False)
    op.create_table('trackingconfig',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackingconfig_config_type'), 'trackingconfig', ['config_type'], unique=False)
    op.create_index(op.f('ix_trackingconfig_name'), 'trackingconfig', ['name'], unique=False)
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_gallery_track_person_id'), table_name='gallery_track')
    op.drop_index(op.f('ix_gallery_track_tracker_id'), table_name='gallery_track')
    op.drop_table('gallery_track')
    op.add_column('camera', sa.Column('network_id', sa.Integer(), nullable=True))
    op.add_column('camera', sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('camera', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('camera', sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('camera', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('camera', sa.Column('has_calibration', sa.Boolean(), nullable=False))
    op.add_column('camera', sa.Column('calibration_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'camera', 'cameranetwork', ['network_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'camera', type_='foreignkey')
    op.drop_column('camera', 'calibration_path')
    op.drop_column('camera', 'has_calibration')
    op.drop_column('camera', 'fps')
    op.drop_column('camera', 'resolution')
    op.drop_column('camera', 'location')
    op.drop_column('camera', 'source_type')
    op.drop_column('camera', 'network_id')
    op.create_table('gallery_track',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_mapped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cam_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frame_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbox', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lost_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gallery_track_pkey'))
    )
    op.create_index(op.f('ix_gallery_track_tracker_id'), 'gallery_track', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_gallery_track_person_id'), 'gallery_track', ['person_id'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trackingconfig_name'), table_name='trackingconfig')
    op.drop_index(op.f('ix_trackingconfig_config_type'), table_name='trackingconfig')
    op.drop_table('trackingconfig')
    op.drop_index(op.f('ix_gallerytrack_tracker_id'), table_name='gallerytrack')
    op.drop_index(op.f('ix_gallerytrack_person_id'), table_name='gallerytrack')
    op.drop_table('gallerytrack')
    op.drop_table('cameranetwork')
    # ### end Alembic commands ###
