"""create_video_segment_table

Revision ID: 9a6374a9a557
Revises: 42a7b8cf2fa3
Create Date: 2026-01-16 01:51:49.367560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a6374a9a557'
down_revision: Union[str, Sequence[str], None] = '42a7b8cf2fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_segment',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_segment_camera_id'), 'video_segment', ['camera_id'], unique=False)
    op.create_index(op.f('ix_video_segment_start_time'), 'video_segment', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_segment_start_time'), table_name='video_segment')
    op.drop_index(op.f('ix_video_segment_camera_id'), table_name='video_segment')
    op.drop_table('video_segment')
    # ### end Alembic commands ###
