DETECTION:
  name: yolov11
  yolov11:
    model_path: weights/yolo11x.pt
    task: detect
    imgsz: 640
    conf_thres: 0.3
    iou_thres: 0.7
    device: cuda
    classes: 0
    max_det: 300

POSE_ESTIMATION:
  name: rtmpose
  rtmpose:
    device: cuda
    model_path: weights/rtmpose-l_256x192/end2end.onnx
    input_size: [192, 256]

TRACKING:
  name: sort
  sort:
    max_age: 30
    min_hits: 5
    iou_threshold: 0.3
  ocsort:
    det_thresh: 0.4
    max_age: 30
    min_hits: 3
    iou_threshold: 0.3
    delta_t: 3
    asso_func: iou
    inertia: 0.2
    use_byte: False

TRACK_MANAGER:
  is_join_track: True
  smooth_factor: 0.1
  appearance_threshold: 0.5
  GALLERY:
    max_live_time: 24000 # 5 mins
    min_hits: 3
    max_features: 50
  MATCHING:
    distance_threshold: 0.5
  EMBEDDING:
    name: onnx_reid
    fastreid: configs/osnet-ain_x1.0-ibn_512_256x192_ccdmmps.yaml
    onnx_reid:
      model_path: weights/ViT-B-16_30.onnx   # <-- fill in your .onnx path
      device: cuda
      input_size: [256, 128]   # [H, W] — height=256, width=128
      mean: [127.5, 127.5, 127.5]
      std:  [127.5, 127.5, 127.5]
      # norm_type: half   # uncomment if model was trained with 0-1 via /255 style



